import React, { useState, useEffect } from 'react';
import { FileTreePanel, type FileNode } from './FileTreePanel';
import { CodeViewer } from './CodeViewer';
import { CodePreview } from './CodePreview';
import { getRunArtifacts } from '@/src/lib/api';

type Artifact = {
  path: string;
  content: string;
  language?: string;
};

type ArtifactsData = {
  run_id: string;
  artifacts: {
    backend?: Artifact[];
    frontend?: Artifact[];
    tests?: Artifact[];
    infra?: Artifact[];
    docs?: Artifact[];
  };
  updated_at?: string;
};

type CodeCanvasProps = {
  runId: string | null;
  visible?: boolean;
};

// Convert flat artifacts list to tree structure
const buildFileTree = (artifacts: ArtifactsData['artifacts']): FileNode[] => {
  const tree: FileNode[] = [];

  Object.entries(artifacts).forEach(([category, files]) => {
    if (!files || files.length === 0) return;

    const categoryNode: FileNode = {
      path: category,
      name: category,
      type: 'folder',
      children: files.map(file => ({
        path: file.path,
        name: file.path.split('/').pop() || file.path,
        type: 'file',
        language: file.language,
      })),
    };

    tree.push(categoryNode);
  });

  return tree;
};

export const CodeCanvas: React.FC<CodeCanvasProps> = ({ runId, visible = true }) => {
  const [fileTree, setFileTree] = useState<FileNode[]>([]);
  const [selectedFile, setSelectedFile] = useState<string | null>(null);
  const [fileContent, setFileContent] = useState<string>('');
  const [fileName, setFileName] = useState<string>('');
  const [language, setLanguage] = useState<string>('plaintext');
  const [showPreview, setShowPreview] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [artifactsData, setArtifactsData] = useState<ArtifactsData['artifacts'] | null>(null);

  // Load artifacts when runId changes
  useEffect(() => {
    if (!runId || !visible) return;

    const loadArtifacts = async () => {
      setLoading(true);
      setError(null);

      try {
        const data = await getRunArtifacts(runId);
        setArtifactsData(data.artifacts);
        setFileTree(buildFileTree(data.artifacts));
      } catch (err) {
        console.error('Failed to load artifacts:', err);
        setError(err instanceof Error ? err.message : 'Failed to load artifacts');
        
        // Mock data for development
        const mockData: ArtifactsData['artifacts'] = {
          backend: [
            { path: 'backend/app.py', content: '# Flask application\nfrom flask import Flask\n\napp = Flask(__name__)\n\n@app.route("/")\ndef home():\n    return "Hello, World!"\n', language: 'python' },
            { path: 'backend/models.py', content: '# Database models\nfrom sqlalchemy import Column, String\n\nclass User:\n    id = Column(String, primary_key=True)\n    name = Column(String)\n', language: 'python' },
          ],
          frontend: [
            { path: 'frontend/App.tsx', content: '// React application\nimport React from "react";\n\nfunction App() {\n  return <div>Hello, World!</div>;\n}\n\nexport default App;', language: 'tsx' },
            { path: 'frontend/index.html', content: '<!DOCTYPE html>\n<html>\n<head>\n  <title>Demo App</title>\n</head>\n<body>\n  <div id="root"></div>\n  <h1 style="color: #E5484D;">Hello from Code Canvas!</h1>\n</body>\n</html>', language: 'html' },
          ],
          tests: [
            { path: 'tests/test_app.py', content: '# Unit tests\nimport unittest\n\nclass TestApp(unittest.TestCase):\n    def test_home(self):\n        assert True\n', language: 'python' },
          ],
          docs: [
            { path: 'docs/README.md', content: '# Project Documentation\n\nThis is a sample project generated by Crew-7.\n\n## Features\n- Backend API\n- Frontend UI\n- Tests\n', language: 'markdown' },
          ],
        };
        setArtifactsData(mockData);
        setFileTree(buildFileTree(mockData));
      } finally {
        setLoading(false);
      }
    };

    void loadArtifacts();
  }, [runId, visible]);

  // Load file content when selected
  useEffect(() => {
    if (!selectedFile || !artifactsData) return;

    // Find file in artifacts
    let foundFile: Artifact | undefined;
    
    Object.values(artifactsData).forEach((files) => {
      if (!files || !Array.isArray(files)) return;
      const file = files.find((f: Artifact) => f.path === selectedFile);
      if (file) foundFile = file;
    });

    if (foundFile) {
      setFileContent(foundFile.content);
      setFileName(foundFile.path.split('/').pop() || foundFile.path);
      setLanguage(foundFile.language || 'plaintext');
    }
  }, [selectedFile, artifactsData]);

  if (!visible) return null;

  if (!runId) {
    return (
      <div className="h-full flex items-center justify-center bg-[#0a0f16]">
        <div className="text-center">
          <div className="text-6xl mb-4">📦</div>
          <h3 className="text-lg font-semibold text-white mb-2">No Run Selected</h3>
          <p className="text-sm text-[#8d96b3]">Start a crew run to view generated artifacts</p>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="h-full flex items-center justify-center bg-[#0a0f16]">
        <div className="text-center">
          <div className="w-12 h-12 border-4 border-[#E5484D]/20 border-t-[#E5484D] rounded-full animate-spin mb-4"></div>
          <p className="text-sm text-[#8d96b3]">Loading artifacts...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="h-full flex bg-[#0a0f16] rounded-2xl border border-white/10 overflow-hidden">
      {/* File Tree */}
      <FileTreePanel
        files={fileTree}
        selectedFile={selectedFile}
        onSelectFile={setSelectedFile}
      />

      {/* Code Viewer */}
      {selectedFile && fileContent ? (
        <div className={`flex-1 flex ${showPreview ? 'w-1/2' : 'w-full'}`}>
          <CodeViewer
            code={fileContent}
            language={language}
            fileName={fileName}
            showPreview={showPreview}
            onTogglePreview={() => setShowPreview(!showPreview)}
          />

          {/* Preview Panel */}
          {showPreview && (
            <div className="w-1/2">
              <CodePreview
                code={fileContent}
                language={language}
                fileName={fileName}
              />
            </div>
          )}
        </div>
      ) : (
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className="text-6xl mb-4">👈</div>
            <h3 className="text-lg font-semibold text-white mb-2">Select a File</h3>
            <p className="text-sm text-[#8d96b3]">Choose a file from the tree to view its contents</p>
          </div>
        </div>
      )}
    </div>
  );
};
