FROM python:3.11-slim
WORKDIR /app
COPY ./app /app/app
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY worker.py /app/worker.py
EXPOSE 8000
CMD ["gunicorn","-k","uvicorn.workers.UvicornWorker","app.main:app","-b","0.0.0.0:8000","--workers","4","--timeout","120"]
